### ISSUE TITLE
Feature request: don't show milliseconds

### ISSUE THREAD

**Issue by stevewillard** [rgommezz/react-native-animated-stopwatch-timer#3]
Hi there! Great library. Would it be possible to add prop to only show minutes and seconds? Thanks!

**Comment by rgommezz** [comment]
Hi @stevewillard! Feel free to open a PR to extend the functionality with a new prop. It should be relatively easy 🙂

**Comment by rgommezz** [comment]
Just set the `trailingZeros` prop to `0`
