### ISSUE TITLE
Feature request: start the timer with an initial time, but continue counting up

### ISSUE THREAD

**Issue by stevewillard** [rgommezz/react-native-animated-stopwatch-timer#4]
I have a use case where I want to store the previous time from a stopwatch, and continue counting up. Would it be possible to make a more explicit "mode" prop instead of `initialTimeInMs`? Thanks!

**Comment by rgommezz** [comment]
I don't have time to extend the library atm, but any PRs are more than welcome!

**Comment by FaysalBsata** [comment]
it's a shame really, its a really good component it should support this

**Comment by rgommezz** [comment]
A new `mode` prop has been added to control the component mode.

Available on the latest version https://github.com/rgommezz/react-native-animated-stopwatch-timer/releases/tag/v1.1.0
