### ISSUE TITLE
Android low fps

### ISSUE THREAD

**Issue by devoren** [rgommezz/react-native-animated-stopwatch-timer#7]
Hello! Thanks for the wonderful library! On Android the timer mode is blocking my js and I can't do anything 😢 with my custom countDown that uses useState fps being around 52-55 fps but I have multiple timers of around 10 on the page so I tried this library. Works fine but js is blocked :(

<img width="335" alt="image" src="https://github.com/rgommezz/react-native-animated-stopwatch-timer/assets/99968085/089f4ea8-cd33-462b-b84a-fcb76d80e049">

**Comment by rgommezz** [comment]
From version 1.3.0 onwards, you can use the `intervalMs` prop to decrease the frequency at which the interval fires to update the timer, in combination with `trailingZeros`.

Looking at your screenshot, probably a good configuration could be:
`intervalMs = 100`
`trailingZeros = 1`
